# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "master","dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: try to build my code
      run: dotnet build
    # Runs a single command using the runners shell 
    - name: Run a one-line script 
      run: echo Hello, world! 
    # Runs a set of commands using the runners shell 
    - name: Run a multi-line script
      run: | 
        echo Add other actions to build, 
        echo test, and deploy your project.
