# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "master","dev" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: try to build my code
      run: dotnet build

    - name: Run unit tests on my code 
      run: dotnet test -v n

    # Runs a single command using the runners shell 
    - name: Run a one-line script 
      run: echo Hello, world! 
    # Runs a set of commands using the runners shell 
    - name: Run a multi-line script
      run: | 
        echo Add other actions to build, 
        echo test, and deploy your project.
